# Generated by Django 3.2.9 on 2021-11-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('favicon', models.ImageField(upload_to='')),
                ('appleicon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Your name', max_length=100)),
                ('lastname', models.CharField(help_text='Your surname', max_length=100)),
                ('display_text', models.TextField(help_text="What text should appear on your site's landing page", max_length=200)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('age', models.PositiveIntegerField(blank=True)),
                ('bio', models.TextField(help_text='Some information about you')),
                ('background_image', models.ImageField(help_text='The image that appears at the background of your site', upload_to='')),
                ('about_image', models.ImageField(help_text='The image that appears at the about', upload_to='')),
                ('address', models.CharField(max_length=200)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_info', to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.myinformation')),
            ],
        ),
    ]
