# Generated by Django 3.2.9 on 2021-11-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='nickname',
            field=models.CharField(default='ogulu', max_length=50),
            preserve_default=False,
        ),
    ]
