# Generated by Django 3.2.9 on 2021-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_myinformation_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='degree',
            field=models.CharField(choices=[('olevel', 'Olevel'), ('undergrad', 'Undegraduate'), ('beng', 'B.Eng'), ('bsc', 'B.Sc'), ('meng', 'Master'), ('phd', 'PHD')], default='olevel', max_length=15),
            preserve_default=False,
        ),
    ]
