# Generated by Django 3.2.9 on 2021-11-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_myinformation_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='occupation',
            field=models.CharField(default='Engineer', help_text='what you do for a living', max_length=50),
            preserve_default=False,
        ),
    ]
