# Generated by Django 3.2.9 on 2021-11-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_myinformation_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='quote',
            field=models.TextField(default='A life lived for others is a life worthwhile.', help_text='your favourite quote'),
            preserve_default=False,
        ),
    ]
