# Generated by Django 3.2.9 on 2021-11-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211119_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(help_text='how good you are at doing it in percentage(Note: Do not include `%`)'),
        ),
    ]
