# Generated by Django 3.2.9 on 2021-11-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_skill_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('testimony', models.TextField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.myinformation')),
            ],
        ),
    ]
