# Generated by Django 3.2.9 on 2021-11-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="name of the service you're providing", max_length=100)),
                ('description', models.CharField(help_text='brief info of what the service is about', max_length=100)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.myinformation')),
            ],
        ),
    ]
