# Generated by Django 3.2.9 on 2021-11-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_birthdaywish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdaywish',
            old_name='relelationship',
            new_name='relationship',
        ),
    ]
