# Generated by Django 3.2.9 on 2021-11-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211120_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
