# Generated by Django 3.2.9 on 2021-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_myimage_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'project categories',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='PictureCategory',
        ),
        migrations.AlterModelOptions(
            name='picturecategory',
            options={'verbose_name_plural': 'picture categories'},
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(to='core.ProjectCategory'),
        ),
    ]
