# Generated by Django 3.2.9 on 2021-11-20 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20211120_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 20, 16, 9, 59, 694425, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
