# Generated by Django 3.2.9 on 2021-11-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_message_created_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalExperience',
            new_name='ProfessionalExperience',
        ),
        migrations.AlterField(
            model_name='myinformation',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='leave empty. it is automatically generated'),
        ),
    ]
