# Generated by Django 3.2.9 on 2021-11-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20211120_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinformation',
            name='about_image',
            field=models.ImageField(blank=True, help_text='The image that appears at the about', upload_to=''),
        ),
        migrations.AlterField(
            model_name='myinformation',
            name='background_image',
            field=models.ImageField(blank=True, help_text='The image that appears at the background of your site', upload_to=''),
        ),
    ]
