# Generated by Django 3.2.9 on 2021-12-02 00:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_transation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transation',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
