# Generated by Django 3.2.9 on 2021-12-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_transation_transaction_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transation',
            new_name='Transaction',
        ),
    ]
